<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class FinishedProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Classic T-Shirts',
                'description' => 'A timeless t-shirt made from 100% organic cotton.',
                'category' => 'Casual Tops',
                'material' => 'Organic Cotton',
                'base_price' => 15.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'White, Red, Brown,and many other colors',
                'stock_quantity' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
            'name' => 'Classic Shirts',
                'description' => 'A timeless shirt made from 100% organic cotton.',
                'category' => 'Formal Tops',
                'material' => 'Organic Cotton',
                'base_price' => 20.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'White, Red, Brown,and many other colors',
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1561053720-76cd73ff22c3?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Suits',
                'description' => 'Formal and casual suits for all purposes.',
                'category' => 'Formal wear',
                'material' => 'All usable material',
                'base_price' => 99.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'Gray, Black, and other colors',
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1582404510421-de6290209c8f?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Denim Jeans',
                'description' => 'Comfortable and stylish blue denim jeans for everyday wear.',
                'category' => 'Bottoms',
                'material' => 'Denim',
                'base_price' => 39.99,
                'size_range' => '28,30,32,34,36',
                'color_options' => 'Blue, Black, Faded',
                'stock_quantity' => 150,
                'image_url' => 'https://images.unsplash.com/photo-1715865871494-6bba579c2dc0?q=80&w=385&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Black Leather Jacket',
                'description' => 'A premium black leather jacket for a bold look.',
                'category' => 'Outerwear',
                'material' => 'Genuine Leather',
                'base_price' => 120.00,
                'size_range' => 'M,L,XL',
                'color_options' => 'Black',
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?q=80&w=380&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Summer Floral Dresses',
                'description' => 'A light and breezy floral dress perfect for summer.',
                'category' => 'Dresses',
                'material' => 'Rayon',
                'base_price' => 29.99,
                'size_range' => 'S,M,L',
                'color_options' => 'Floral',
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1583316174775-bd6dc0e9f298?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Hooded Sweatshirts',
                'description' => 'A cozy hooded sweatshirt perfect for chilly days.',
                'category' => 'Hoodies',
                'material' => 'Fleece',
                'base_price' => 35.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'Gray, Black, Navy',
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1680292783974-a9a336c10366?q=80&w=394&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'CropTops',
                'description' => 'A cozy and perfect for chilly and sunny days.',
                'category' => 'Tops',
                'material' => 'Cotton',
                'base_price' => 10.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'Red, Black, White, Black, and others',
                'stock_quantity' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1673837557599-c2def5cdc4c2?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Cotton Fabric',
                'description' => 'High-quality raw cotton fabric for garment production.',
                'category' => 'Fabric',
                'material' => 'Cotton',
                'base_price' => 4.99,
                'size_range' => 'Rolls, Sheets',
                'color_options' => 'White, Off-white',
                'stock_quantity' => 500,
                'image_url' => 'https://images.unsplash.com/photo-1630920501459-f3e99320c4a5?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Denim Fabric',
                'description' => 'Durable denim fabric for jeans and jackets.',
                'category' => 'Fabric',
                'material' => 'Denim',
                'base_price' => 7.99,
                'size_range' => 'Rolls',
                'color_options' => 'Blue, Black',
                'stock_quantity' => 300,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1673310539494-cb7d161d364c?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Leather Sheets',
                'description' => 'Premium leather sheets for jackets and accessories.',
                'category' => 'Material',
                'material' => 'Leather',
                'base_price' => 19.99,
                'size_range' => 'Sheets',
                'color_options' => 'Black, Brown',
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1573227896778-8f378c4029d4?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Polyester Thread',
                'description' => 'Strong polyester thread for sewing garments.',
                'category' => 'Thread',
                'material' => 'Polyester',
                'base_price' => 1.99,
                'size_range' => 'Spools',
                'color_options' => 'White, Black, Red, Blue',
                'stock_quantity' => 1000,
                'image_url' => 'https://images.unsplash.com/photo-1654007140234-90dc9013667c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDl8fHxlbnwwfHx8fHw%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Metal Zippers',
                'description' => 'Durable metal zippers for jackets and jeans.',
                'category' => 'Accessories',
                'material' => 'Metal',
                'base_price' => 0.49,
                'size_range' => '10cm, 15cm, 20cm',
                'color_options' => 'Silver, Gold, Black',
                'stock_quantity' => 2000,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1674718916934-b8522d253fb1?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Checked Shirts',
                'description' => 'Comfortable and stylish checked shirts for everyday wear.',
                'category' => 'Casual Wear',
                'material' => 'Dyes, Cotton',
                'base_price' => 49.99,
                'size_range' => '6,7,8,9,10,11',
                'color_options' => 'All colors',
                'stock_quantity' => 120,
                'image_url' => 'https://images.unsplash.com/photo-1588795904317-2f4ab1a0a852?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Woolen Scarves',
                'description' => 'Soft woolen scarves for winter.',
                'category' => 'Accessories',
                'material' => 'Wool',
                'base_price' => 14.99,
                'size_range' => 'One Size',
                'color_options' => 'Red, Gray, Blue',
                'stock_quantity' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1731399211410-e3ffe1560310?q=80&w=436&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Pleated Skirts',
                'description' => 'Elegant pleated skirts for formal and casual occasions.',
                'category' => 'Bottoms',
                'material' => 'Polyester',
                'base_price' => 24.99,
                'size_range' => 'S,M,L',
                'color_options' => 'Black, Navy, Pink',
                'stock_quantity' => 90,
                'image_url' => 'https://images.unsplash.com/photo-1685953851497-9b67b25f0ed7?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Office Skirts',
                'description' => 'Fashionable office skirts for formal looks.',
                'category' => 'Formal Wear',
                'material' => 'All materials',
                'base_price' => 20.99,
                'size_range' => 'All Sizes',
                'color_options' => 'All Colors',
                'stock_quantity' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1649315324621-3d63b5aae680?q=80&w=876&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Blazers',
                'description' => 'Smart blazers for business and formal events.',
                'category' => 'Outerwear',
                'material' => 'Polyester Blend',
                'base_price' => 59.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'Black, Navy, Gray',
                'stock_quantity' => 70,
                'image_url' => 'https://images.unsplash.com/photo-1740710370552-a49b5b01f80a?q=80&w=498&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            // New raw materials
            [
                'name' => 'Silk Fabric',
                'description' => 'Luxurious silk fabric for premium garments.',
                'category' => 'Fabric',
                'material' => 'Silk',
                'base_price' => 24.99,
                'size_range' => 'Rolls, Sheets',
                'color_options' => 'White, Red, Blue',
                'stock_quantity' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1732392334727-e78570f1d1bc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDZ8fHxlbnwwfHx8fHw%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Wooden Buttons',
                'description' => 'Eco-friendly wooden buttons for shirts and jackets.',
                'category' => 'Accessories',
                'material' => 'Wood',
                'base_price' => 0.19,
                'size_range' => 'Small, Medium, Large',
                'color_options' => 'Natural Wood',
                'stock_quantity' => 1500,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1670044658549-0f513915e2e1?q=80&w=869&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Elastic Bands',
                'description' => 'Durable elastic bands for waistbands and cuffs.',
                'category' => 'Accessories',
                'material' => 'Elastic',
                'base_price' => 0.29,
                'size_range' => '1cm, 2cm, 3cm',
                'color_options' => 'White, Black',
                'stock_quantity' => 2000,
                'image_url' => 'https://images.unsplash.com/photo-1672804591677-e859bf816875?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGVsYXN0aWMlMjBiYW5kcyUyMGZvciUyMGNsb3RoaW5nfGVufDB8fDB8fHww',
                'is_active' => true,
                'type' => 'raw_material',
            ],
        ];

        foreach ($products as $product) {
            Item::create($product);
        }
    }
}
