<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class FinishedProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Classic T-Shirts',
                'description' => 'A timeless t-shirt made from 100% organic cotton.',
                'category' => 'Casual Tops',
                'material' => 'Organic Cotton',
                'base_price' => 15.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'White, Red, Brown,and many other colors',
                'stock_quantity' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
            'name' => 'Classic Shirts',
                'description' => 'A timeless shirt made from 100% organic cotton.',
                'category' => 'Formal Tops',
                'material' => 'Organic Cotton',
                'base_price' => 20.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'White, Red, Brown,and many other colors',
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1561053720-76cd73ff22c3?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Suits',
                'description' => 'Formal and casual suits for all purposes.',
                'category' => 'Formal wear',
                'material' => 'All usable material',
                'base_price' => 99.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'Gray, Black, and other colors',
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1582404510421-de6290209c8f?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Denim Jeans',
                'description' => 'Comfortable and stylish blue denim jeans for everyday wear.',
                'category' => 'Bottoms',
                'material' => 'Denim',
                'base_price' => 39.99,
                'size_range' => '28,30,32,34,36',
                'color_options' => 'Blue, Black, Faded',
                'stock_quantity' => 150,
                'image_url' => 'https://images.unsplash.com/photo-1715865871494-6bba579c2dc0?q=80&w=385&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Black Leather Jacket',
                'description' => 'A premium black leather jacket for a bold look.',
                'category' => 'Outerwear',
                'material' => 'Genuine Leather',
                'base_price' => 120.00,
                'size_range' => 'M,L,XL',
                'color_options' => 'Black',
                'stock_quantity' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?q=80&w=380&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Summer Floral Dresses',
                'description' => 'A light and breezy floral dress perfect for summer.',
                'category' => 'Dresses',
                'material' => 'Rayon',
                'base_price' => 29.99,
                'size_range' => 'S,M,L',
                'color_options' => 'Floral',
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1583316174775-bd6dc0e9f298?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Hooded Sweatshirts',
                'description' => 'A cozy hooded sweatshirt perfect for chilly days.',
                'category' => 'Hoodies',
                'material' => 'Fleece',
                'base_price' => 35.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'Gray, Black, Navy',
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1680292783974-a9a336c10366?q=80&w=394&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'CropTops',
                'description' => 'A cozy and perfect for chilly and sunny days.',
                'category' => 'Tops',
                'material' => 'Cotton',
                'base_price' => 10.99,
                'size_range' => 'S,M,L,XL',
                'color_options' => 'Red, Black, White, Black, and others',
                'stock_quantity' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1673837557599-c2def5cdc4c2?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'finished_product',
            ],
            [
                'name' => 'Cotton Fabric',
                'description' => 'High-quality raw cotton fabric for garment production.',
                'category' => 'Fabric',
                'material' => 'Cotton',
                'base_price' => 4.99,
                'size_range' => 'Rolls, Sheets',
                'color_options' => 'White, Off-white',
                'stock_quantity' => 500,
                'image_url' => 'https://images.unsplash.com/photo-1630920501459-f3e99320c4a5?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Denim Fabric',
                'description' => 'Durable denim fabric for jeans and jackets.',
                'category' => 'Fabric',
                'material' => 'Denim',
                'base_price' => 7.99,
                'size_range' => 'Rolls',
                'color_options' => 'Blue, Black',
                'stock_quantity' => 300,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1673310539494-cb7d161d364c?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Leather Sheets',
                'description' => 'Premium leather sheets for jackets and accessories.',
                'category' => 'Material',
                'material' => 'Leather',
                'base_price' => 19.99,
                'size_range' => 'Sheets',
                'color_options' => 'Black, Brown',
                'stock_quantity' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1573227896778-8f378c4029d4?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Polyester Thread',
                'description' => 'Strong polyester thread for sewing garments.',
                'category' => 'Thread',
                'material' => 'Polyester',
                'base_price' => 1.99,
                'size_range' => 'Spools',
                'color_options' => 'White, Black, Red, Blue',
                'stock_quantity' => 1000,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1726837257209-ac129836e21b?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
            [
                'name' => 'Metal Zippers',
                'description' => 'Durable metal zippers for jackets and jeans.',
                'category' => 'Accessories',
                'material' => 'Metal',
                'base_price' => 0.49,
                'size_range' => '10cm, 15cm, 20cm',
                'color_options' => 'Silver, Gold, Black',
                'stock_quantity' => 2000,
                'image_url' => 'https://plus.unsplash.com/premium_photo-1674718916934-b8522d253fb1?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => true,
                'type' => 'raw_material',
            ],
        ];

        foreach ($products as $product) {
            Item::create($product);
        }
    }
}
